name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run tests
        run: go test -cover  ./...

  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Config staticcheck
        run: echo "$GOPATH/bin" >> $GITHUB_PATH


      - name: Run go fmt
        run: test -z $(go fmt ./...)
      
      - name: Linting with staticcheck
        run: staticcheck ./...
